#注册中心的信息
spring:
  application:
    name: mall-getway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
#测试网关路由规则配置
    gateway:
      routes:
        - id: router1
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: router2
          uri: https://www.jd.com
          predicates:
            - Query=url,jd
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/app/product/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: app_route
          uri: lb://renren-fast
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /renren-fast/$\{segment}
# localhost:8070/app/captcha.jpg -->
# localhost:8080/app/captcha.jpg localhost:8080/renren-fast/captcha.jpg
#指定注册中心的服务端口
server:
  port: 8070
